import type { NpcState, PlayerState } from './State.js';

export type PlayerCompute = {
    readonly x: number;
    readonly level: number;
    readonly z: number;
    readonly originX: number;
    readonly originZ: number;
    readonly pid: number;
    readonly tele: boolean;
    readonly jump: boolean;
    readonly runDir: number;
    readonly walkDir: number;
    readonly visibility: PlayerState['visibility'];
    readonly active: boolean;
    readonly masks: number;
    readonly appearance: Uint8Array;
    readonly lastAppearance: number;
    readonly faceEntity: number;
    readonly faceX: number;
    readonly faceZ: number;
    readonly orientationX: number;
    readonly orientationZ: number;
    readonly damageTaken: number;
    readonly damageType: number;
    readonly damageTaken2: number;
    readonly damageType2: number;
    readonly currentHitpoints: number;
    readonly baseHitpoints: number;
    readonly animId: number;
    readonly animDelay: number;
    readonly say: string | null;
    readonly message: Uint8Array | null;
    readonly color: number;
    readonly effect: number;
    readonly ignored: number;
    readonly graphicId: number;
    readonly graphicHeight: number;
    readonly graphicDelay: number;
    readonly exactStartX: number;
    readonly exactStartZ: number;
    readonly exactEndX: number;
    readonly exactEndZ: number;
    readonly exactMoveStart: number;
    readonly exactMoveEnd: number;
    readonly exactMoveDirection: number;
};

export type NpcCompute = {
    readonly x: number;
    readonly level: number;
    readonly z: number;
    readonly nid: number;
    readonly type: number;
    readonly tele: boolean;
    readonly jump: boolean;
    readonly runDir: number;
    readonly walkDir: number;
    readonly active: boolean;
    readonly masks: number;
    readonly faceEntity: number;
    readonly faceX: number;
    readonly faceZ: number;
    readonly orientationX: number;
    readonly orientationZ: number;
    readonly damageTaken: number;
    readonly damageType: number;
    readonly damageTaken2: number;
    readonly damageType2: number;
    readonly currentHitpoints: number;
    readonly baseHitpoints: number;
    readonly animId: number;
    readonly animDelay: number;
    readonly say: string | null;
    readonly graphicId: number;
    readonly graphicHeight: number;
    readonly graphicDelay: number;
};

export function updatePlayerState(player: PlayerState, input: PlayerCompute): void {
    player.coord = { packed: ((input.z & 0x3fff) | ((input.x & 0x3fff) << 14) | ((input.level & 0x3) << 28)) >>> 0, x: input.x & 0x3fff, level: input.level & 0x3, z: input.z & 0x3fff };
    player.origin = { packed: ((input.originZ & 0x3fff) | ((input.originX & 0x3fff) << 14) | ((input.level & 0x3) << 28)) >>> 0, x: input.originX & 0x3fff, level: input.level & 0x3, z: input.originZ & 0x3fff };
    player.tele = input.tele;
    player.jump = input.jump;
    player.runDir = input.runDir;
    player.walkDir = input.walkDir;
    player.visibility = input.visibility;
    player.active = input.active;
    player.masks = input.masks;
    player.appearance = new Uint8Array(input.appearance);
    player.lastAppearance = input.lastAppearance;
    player.faceEntity = input.faceEntity;
    player.faceX = input.faceX;
    player.faceZ = input.faceZ;
    player.orientationX = input.orientationX;
    player.orientationZ = input.orientationZ;
    player.damageTaken = input.damageTaken;
    player.damageType = input.damageType;
    player.damageTaken2 = input.damageTaken2;
    player.damageType2 = input.damageType2;
    player.currentHitpoints = input.currentHitpoints;
    player.baseHitpoints = input.baseHitpoints;
    player.animId = input.animId;
    player.animDelay = input.animDelay;
    player.say = input.say;
    player.chat = input.message ? { bytes: new Uint8Array(input.message), color: input.color, effect: input.effect, ignored: input.ignored } : null;
    player.graphicId = input.graphicId;
    player.graphicHeight = input.graphicHeight;
    player.graphicDelay = input.graphicDelay;
    player.exactMove = input.exactStartX === -1 ? null : { startX: input.exactStartX, startZ: input.exactStartZ, endX: input.exactEndX, endZ: input.exactEndZ, begin: input.exactMoveStart, finish: input.exactMoveEnd, direction: input.exactMoveDirection };
}

export function updateNpcState(npc: NpcState, input: NpcCompute): void {
    npc.coord = { packed: ((input.z & 0x3fff) | ((input.x & 0x3fff) << 14) | ((input.level & 0x3) << 28)) >>> 0, x: input.x & 0x3fff, level: input.level & 0x3, z: input.z & 0x3fff };
    npc.type = input.type;
    npc.tele = input.tele;
    npc.jump = input.jump;
    npc.runDir = input.runDir;
    npc.walkDir = input.walkDir;
    npc.active = input.active;
    npc.masks = input.masks;
    npc.faceEntity = input.faceEntity;
    npc.faceX = input.faceX;
    npc.faceZ = input.faceZ;
    npc.orientationX = input.orientationX;
    npc.orientationZ = input.orientationZ;
    npc.damageTaken = input.damageTaken;
    npc.damageType = input.damageType;
    npc.damageTaken2 = input.damageTaken2;
    npc.damageType2 = input.damageType2;
    npc.currentHitpoints = input.currentHitpoints;
    npc.baseHitpoints = input.baseHitpoints;
    npc.animId = input.animId;
    npc.animDelay = input.animDelay;
    npc.say = input.say;
    npc.graphicId = input.graphicId;
    npc.graphicHeight = input.graphicHeight;
    npc.graphicDelay = input.graphicDelay;
}
